services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./data:/app/data/neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:7474"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s

  stardewkg:
    build:
      context: .
    container_name: stardewkg
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - DATA_FOLDER_WIKILINKS=/app/data/wiki/sources
      - NEO4J_URI=bolt://neo4j:7687
    restart: "no"
